//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FetihlerV2Entities1 : DbContext
    {
        public FetihlerV2Entities1()
            : base("name=FetihlerV2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Araclar> tbl_Araclar { get; set; }
        public virtual DbSet<tbl_Bolgeler> tbl_Bolgeler { get; set; }
        public virtual DbSet<tbl_Donemler> tbl_Donemler { get; set; }
        public virtual DbSet<tbl_Hastaliklar> tbl_Hastaliklar { get; set; }
        public virtual DbSet<tbl_Kategoriler> tbl_Kategoriler { get; set; }
        public virtual DbSet<tbl_Kisiler> tbl_Kisiler { get; set; }
        public virtual DbSet<tbl_Koyler> tbl_Koyler { get; set; }
        public virtual DbSet<tbl_Maaslar> tbl_Maaslar { get; set; }
        public virtual DbSet<tbl_Gorevliler> tbl_Gorevliler { get; set; }
        public virtual DbSet<tbl_Erzaklar> tbl_Erzaklar { get; set; }
    }
}
