//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Erzaklar
    {
        public int ErzakNo { get; set; }
        public string ErzakAdi { get; set; }
        public Nullable<int> DonemNo { get; set; }
    
        public virtual tbl_Donemler tbl_Donemler { get; set; }
    }
}
