//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kisiler
    {
        public int KisiNo { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyAd { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string MedeniHal { get; set; }
        public string Cinsiyet { get; set; }
        public string EvDurumu { get; set; }
        public string AraziDurumu { get; set; }
        public string BüyükBas { get; set; }
        public string KücükBas { get; set; }
        public string BakımDurumu { get; set; }
        public string IsDurumu { get; set; }
        public string EkBilgi { get; set; }
        public Nullable<int> Hastalik { get; set; }
        public Nullable<int> Koy { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<bool> Seç { get; set; }
        public Nullable<int> Maas { get; set; }
        public string TcNo { get; set; }
        public Nullable<int> Referans { get; set; }
        public string AileYakınları { get; set; }
    
        public virtual tbl_Hastaliklar tbl_Hastaliklar { get; set; }
        public virtual tbl_Kategoriler tbl_Kategoriler { get; set; }
        public virtual tbl_Koyler tbl_Koyler { get; set; }
        public virtual tbl_Maaslar tbl_Maaslar { get; set; }
        public virtual tbl_Gorevliler tbl_Gorevliler { get; set; }
    }
}
