//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bolgeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bolgeler()
        {
            this.tbl_Koyler = new HashSet<tbl_Koyler>();
        }
    
        public int BolgeNo { get; set; }
        public string BolgeAdi { get; set; }
        public string BolgeAciklama { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public string BolgeSorumlusu { get; set; }
        public string BolgeYardımcısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Koyler> tbl_Koyler { get; set; }
    }
}
