//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FethlerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Araclar
    {
        public int AracNo { get; set; }
        public string AracAdi { get; set; }
        public Nullable<int> AracSahip { get; set; }
        public Nullable<bool> Seç { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<int> AracKapasite { get; set; }
    
        public virtual tbl_Gorevliler tbl_Gorevliler { get; set; }
    }
}
